# Music Recommendation System

# Dataset information

Million song dataset contain two files : triplet files and metadata file.triplet file contain user_id, song_id, listern time.
The metadatafile contains song_id, release, year, title and artist_name.Million song Dataset is a mixture of  song from various
website with the rating that users gave after listening the songs.

There are three type of recommendation system : content-based, collaborative and popularity.
    content-based:- use keywords for recommendation.
    collaborative:- if one user hear two common songs and second user hear another third song then it will suggest to first 
                    user to hear that song.
    popularity:- Based on the stars and review of public it will suggest the song.

# Import Datasets

In [1]:
import pandas as pd
import numpy as np
import recommender as recommender

# Loading the datasets

In [3]:
song_df_1 = pd.read_csv('triplets_file.csv')
song_df_1.head()
#head()-used to return top n rows of dataframes or series.by default n=5.

                                    user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

In [5]:
song_df_2 = pd.read_csv('song_data.csv')
song_df_2.head()

,song_id,title,release,artist_name,year
0,SOQMMHC12AB0180CB8,Silent Night,Monster Ballads X-Mas,Faster Pussy cat,2003
1,SOVFVAK12A8C1350D9,Tanssi vaan,Karkuteillä,Karkkiautomaatti,1995
2,SOGTUKN12AB017F4F1,No One Could Ever,Butter,Hudson Mohawke,2006
3,SOBNYVR12A8C13558C,Si Vos Querés,De Culo,Yerba Brava,2003
4,SOHSBXH12A8C13B0DF,Tangle Of Aspens,Rene Ablaze Presents Winter Sessions,Der Mystic,0

# Data Preprocessing

In [7]:
#merging two dataframe with removing duplicates from second frame
song_df = pd.merge(song_df_1, song_df_2.drop_duplicates(['song_id']), on='song_id',how = 'left')
song_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999

In [8]:
#finding length of dataframe
len(song_df)

2000000

In [11]:
#merging to frame that are title and artist name and make one frame named as song
song_df['song'] = song_df['title']+'-'+song_df['artist_name']
song_df.head()

,user_id,song_id,listen_count,title,release,artist_name,year,song
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,The Cove,Thicker Than Water,Jack Johnson,0,The Cove-Jack Johnson
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,Entre Dos Aguas,Flamenco Para Niños,Paco De Lucia,1976,Entre Dos Aguas-Paco De Lucia
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBXHDL12A81C204C0,1,Stronger,Graduation,Kanye West,2007,Stronger-Kanye West
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBYHAJ12A6701BF1D,1,Constellations,In Between Dreams,Jack Johnson,2005,Constellations-Jack Johnson
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SODACBL12A8C13C273,1,Learn To Fly,There Is Nothing Left To Lose,Foo Fighters,1999,Learn To Fly-Foo Fighters

In [14]:
#finding the cummulative sum of listen count of the songs
song_grouped = song_df.groupby(['song']).agg({'listen_count' : 'count'}).reset_index()
song_grouped.head()

                                                song  listen_count
0  #!*@ You Tonight [Featuring R. Kelly] (Explici...            78
1                             #40-DAVE MATTHEWS BAND           338
2                                  & Down-Boys Noize           373
3                            ' Cello Song-Nick Drake           103
4                          '97 Bonnie & Clyde-Eminem            93

In [16]:
grouped_sum = song_grouped['listen_count'].sum()
song_grouped['percentage'] = (song_grouped['listen_count']/grouped_sum) * 100
song_grouped.sort_values(['listen_count','song'],ascending = [0,1])
#here listern count will be sort by descending values bcz we gave 0 but when two values are same it will sort that in ascending order with the help of 1 written over there.

,song,listen_count,percentage
7127,Sehr kosmisch-Harmonia,8277,0.41385
9084,Undo-Björk,7032,0.35160
2068,Dog Days Are Over (Radio Edit)-Florence + The ...,6949,0.34745
9877,You're The One-Dwight Yoakam,6412,0.32060
6774,Revelry-Kings Of Leon,6145,0.30725
...,...,...,...
3526,Historia Del Portero-Ricardo Arjona,51,0.00255
7072,Scared-Three Days Grace,51,0.00255
2147,Don´t Leave Me Now-Amparanoia,50,0.00250
2991,Ghosts (Toxic Avenger Mix)-Ladytron,48,0.00240
5811,No Creo En El Jamas-Juanes,48,0.00240

# Popularity Recommendations model

In [17]:
pr = recommender.popularity_recommender_py()
pr.create(song_df,'user_id','song')
#using this create method from recommender.py file we can able to create the recommendation system

In [18]:
pr.recommend(song_df['user_id'][5])
#will recommend the song for user of 5th num..although it won't affect by user it will show top 10 songs or trending songs from score or rank

,user_id,song,score,Rank
7127,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Sehr kosmisch-Harmonia,8277,1.0
9084,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Undo-Björk,7032,2.0
2068,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Dog Days Are Over (Radio Edit)-Florence + The ...,6949,3.0
9877,b80344d063b5ccb3212f76538f3d9e43d87dca9e,You're The One-Dwight Yoakam,6412,4.0
6774,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Revelry-Kings Of Leon,6145,5.0
7115,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Secrets-OneRepublic,5841,6.0
3613,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Horn Concerto No. 4 in E flat K495: II. Romanc...,5385,7.0
2717,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Fireflies-Charttraxx Karaoke,4795,8.0
3485,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Hey_ Soul Sister-Train,4758,9.0
8847,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Tive Sim-Cartola,4548,10.0

# Item Similarity Recommendations

In [19]:
ir = recommender.item_similarity_recommender_py()
ir.create(song_df,'user_id','song')

In [22]:
#print the song listen by index num 10th user
user_items = ir.get_user_items(song_df['user_id'][5])
for user_item in user_items:
    print(user_item)

The Cove-Jack Johnson
Entre Dos Aguas-Paco De Lucia
Stronger-Kanye West
Constellations-Jack Johnson
Learn To Fly-Foo Fighters
Apuesta Por El Rock 'N' Roll-Héroes del Silencio
Paper Gangsta-Lady GaGa
Stacked Actors-Foo Fighters
Sehr kosmisch-Harmonia
Heaven's gonna burn your eyes-Thievery Corporation feat. Emiliana Torrini
Let It Be Sung-Jack Johnson / Matt Costa / Zach Gill / Dan Lebowitz / Steve Adams
I'll Be Missing You (Featuring Faith Evans & 112)(Album Version)-Puff Daddy
Love Shack-The B-52's
Clarity-John Mayer
I?'m A Steady Rollin? Man-Robert Johnson
The Old Saloon-The Lonely Island
Behind The Sea [Live In Chicago]-Panic At The Disco
Champion-Kanye West
Breakout-Foo Fighters
Ragged Wood-Fleet Foxes
Mykonos-Fleet Foxes
Country Road-Jack Johnson / Paula Fuga
Oh No-Andrew Bird
Love Song For No One-John Mayer
Jewels And Gold-Angus & Julia Stone
Warning-Incubus
83-John Mayer
Neon-John Mayer
The Middle-Jimmy Eat World
High and dry-Jorge Drexler
All That We Perceive-Thievery Corporation
The Christmas Song  (LP Version)-King Curtis
Our Swords (Soundtrack Version)-Band Of Horses
Are You In?-Incubus
Drive-Incubus
Generator-Foo Fighters
Come Back To Bed-John Mayer
He Doesn't Know Why-Fleet Foxes
Trani-Kings Of Leon
Bigger Isn't Better-The String Cheese Incident
Sun Giant-Fleet Foxes
City Love-John Mayer
Right Back-Sublime
Moonshine-Jack Johnson
Holes To Heaven-Jack Johnson

In [23]:
#will recommend the user for 5th user
ir.recommend(song_df['user_id'][5])

No. of unique songs for the user: 45
no. of unique songs in the training set: 9953
Non zero values in cooccurence_matrix :268460

,user_id,song,score,rank
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Quiet Houses-Fleet Foxes,0.034172,1
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Meadowlarks-Fleet Foxes,0.033473,2
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Heard Them Stirring-Fleet Foxes,0.032683,3
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Great Indoors-John Mayer,0.032123,4
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Tiger Mountain Peasant Song-Fleet Foxes,0.031740,5
5,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Sun It Rises-Fleet Foxes,0.031253,6
6,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Your Protector-Fleet Foxes,0.030409,7
7,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Oliver James-Fleet Foxes,0.030237,8
8,b80344d063b5ccb3212f76538f3d9e43d87dca9e,Belle-Jack Johnson,0.028708,9
9,b80344d063b5ccb3212f76538f3d9e43d87dca9e,If I Could-Jack Johnson,0.028350,10

In [ ]:
#there are 45 unique songs from training datasets which user never heared.so based on that system will generate cooccurence_matrix and reccommend song for user from this 45 unique songs.

In [24]:
#give related songs based on the words
ir.get_similar_items(['Ragged Wood-Fleet Foxes'])
#here all the songs related to fleet foxes will be display.

no. of unique songs in the training set: 9953
Non zero values in cooccurence_matrix :6090

  user_id                                     song     score rank
0                         Quiet Houses-Fleet Foxes  0.450142    1
1                          Meadowlarks-Fleet Foxes  0.422535    2
2                  Heard Them Stirring-Fleet Foxes  0.414330    3
3                  He Doesn't Know Why-Fleet Foxes  0.386935    4
4          Tiger Mountain Peasant Song-Fleet Foxes  0.373239    5
5                       Your Protector-Fleet Foxes  0.363171    6
6                         Sun It Rises-Fleet Foxes  0.334000    7
7                         Oliver James-Fleet Foxes  0.328467    8
8                  White Winter Hymnal-Fleet Foxes  0.317940    9
9                   Drops In The River-Fleet Foxes  0.203046   10